import { useCounterStore } from "../../stores/counter.js"
const User = useCounterStore()

//道具編號與圖片編號相關
//
//
//
const Item =[
    {number:"0",
    name:"天信",
    type:'消耗',
    illustrate:'可用以溝通天道的信封，撕碎信封後，文字立即傳送至天道身旁',
    note:'使用後無點擊送出訊息，天信依然會消耗',
    use:()=>{User.Player.letter = true},
    img:'./images/Item/royal _937387.png',
    },
    {number:"000",
    name:"丹丹漢堡",
    type:'消耗',
    illustrate:'呱',
    note:'好吃，靈力增加999999',
    use:()=>{User.Player.power +=999999},
    img:'./images/Item/hamburger.jpeg',
    },
    {number:"001",
    name:"破境神丹",
    type:'消耗',
    illustrate:'任何境界，只要一粒即可突破境界',
    note:'死亡率99.9999%，請自行衡量',
    use:undefined,
    img:'./images/Item/001.jpeg',
    },
    {number:"002",
    name:"天靈丹",
    type:'消耗',
    illustrate:'集蒼天靈氣而成，僅蒼天絕地才可產出',
    note:'境界越高效益越大',
    use:()=>{console.log('use')},
    img:'./images/Item/001.jpeg',
    },
    {number:"003",
    name:"地靈丹",
    type:'消耗',
    illustrate:'集幽冥地靈氣而成，僅幽冥絕地才可產出',
    note:'境界越高效益越大',
    use:()=>{console.log('use')},
    img:'./images/Item/001.jpeg',
    },
    {number:"004",
    name:"天雷棒",
    type:'法具',
    illustrate:'震天降雷',
    note:'一棒震天，二棒滅世',
    use:()=>{alert('無法使用')},
    img:'./images/Item/001.jpeg',
    },
    {number:"005",
    name:"不知明人骨",
    type:'材料',
    illustrate:'疑似化神境修士之骨骸',
    note:'盆骨處寫著『凱文到此一遊』',
    use:()=>{alert('這骨骸...有被啃過的痕跡')},
    img:'./images/Item/bone_6651679.png',
    },
    {number:"006",
    name:"位面破空符",
    type:'位面',
    illustrate:'可穿越位面進行破空移動',
    note:'使用時低機率消耗全部靈力',
    use:()=>{console.log('use')},
    img:'./images/Item/001.jpeg',
    },
    {number:"007",
    name:"天道賜玉",
    type:'消耗',
    illustrate:'遠古天道賜予護道者的青玉，庇護持有者不受天道攻擊。',
    note:'劫運提高999%',
    use:()=>{User.Player.probability +=999},
    img:'./images/Item/001.jpeg',
    },
    {number:"008",
    name:"神元丸",
    type:'法具',
    illustrate:'散發奇特香味的丹丸，氣味具有養神滋元之功效。',
    note:'打坐靈力加成，10/s 靈力',
    use:()=>{User.Player.props = '神元丸'},
    img:'./images/Item/bk169-011.jpeg',
    },
    {number:"009",
    name:"靈兆天鐘",
    type:'法具',
    illustrate:'？？？？？？',
    note:'打坐靈力加成，10000/s 靈力',
    use:()=>{User.Player.props = '靈兆天鐘'},
    img:'./images/Item/001.jpeg',
    },
    {number:"010",
    name:"汲靈石",
    type:'法具',
    illustrate:'汲取大氣靈力的神秘石頭，隨著擁有者的動作而發動。',
    note:'鍛練靈力加成，20/次 靈力',
    use:()=>{User.Player.props = '汲靈石'},
    img:'./images/Item/001.jpeg',
    },
    {number:"011",
    name:"世界碎片",
    type:'位面',
    illustrate:'',
    note:'大量靈力加成，10000/s、20/次 靈力',
    use:()=>{User.Player.props = '世界碎片'},
    img:'./images/Item/001.jpeg',
    },
    
        
]
export default Item;